In [1]:
import numpy as np

## $x^Tw$ ##

In [5]:
a = np.arange(1e3)
b = np.arange(1e3)

%timeit a.dot(b)

706 ns ± 18.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [14]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X.dtype

dtype('int32')

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr = np.array([[3., 2., 1], [4., 5., 6.]])

In [29]:
arr.sum()

21.0

## Broadcasting ##

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = arr[0].copy()
new_arr += 99

In [47]:
new_arr

array([100, 101, 102])

In [48]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [49]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [50]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [56]:
np.concatenate([arr, arr], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [66]:
arr[~(arr > 2)]

array([1, 2])